### ISSUE TITLE
The file is not a valid flow file.

### ISSUE THREAD

**Issue by mrankitaggarwal** [derekdanderson/createdraftarticlefromcase#1]
When I try to upload this flow to my org it gives error:

Invalid File
The file is not a valid flow file.

**Comment by derekdanderson** [comment]
Are you using the Summer 18 commit or the No Record Types commit?

Have you verified the following Prerequisites?

Lighting Knowledge enabled
Knowledge object with an API Name of Knowledge__kav
Configure at least 1 Record Type on Knowledge__kav so that RecordTypeID field exists (if not using Record Types, install branch: norecordtypes)

**Comment by derekdanderson** [comment]
@mrankitaggarwal I have removed the flow definition.   Let me know if that resolves your issue.

**Comment by mrankitaggarwal** [comment]
@derekdanderson Thank you so much for working on this and trying to resolve the problem. Some of the pre-requisites are not met, like the API name is not Knowledge__kav. Is it possible to make it object name independent?
